# Generated by Django 5.0.2 on 2024-02-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Farmer_name', models.CharField(max_length=200)),
                ('Contact_num', models.CharField(max_length=100)),
                ('Email_id', models.EmailField(max_length=200)),
                ('Password', models.PositiveIntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scholar_name', models.CharField(max_length=50)),
                ('Contact_num', models.IntegerField(max_length=13)),
                ('Email_id', models.EmailField(max_length=50)),
                ('Password', models.PositiveIntegerField(max_length=50)),
            ],
        ),
    ]
