# Generated by Django 5.0.2 on 2024-03-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeScreens', '0006_alter_feedback_picture_alter_testimonial_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='picture',
            field=models.ImageField(upload_to='testimonial/'),
        ),
    ]
